.TH jmblr "30th Oct 2018" "1.1" "jmblr man page"
.SH NAME
jmblr \- Solve Jumble Words
.SH SYNONPSIS
jmblr, the program takes user inputs, arranges that by words, and searches the dictionary for matches.
.SH OPTIONS
--help   -h	a help page.

--update -u	update the dictionary database.
.SH AUTHOR
Sourav Goswami (souravgoswami@protonmail.com)
